(add-to-list 'load-path "~/.emacs.d/site-lisp/") 
(require 'auto-install)
(setq auto-install-directory "~/.emacs.d/site-lisp/")
;;(auto-install-update-emacswiki-package-name t) 
(auto-install-compatibility-setup) 
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
