(require 'el-get)

(defvar bootstrap:packages
      '(auto-async-byte-compile
        ac-company
        ace-jump-mode
        anything
        auto-complete
        auto-complete-clang
        auto-complete-etags
        auto-save-buffers-enhanced 
        blockdiag-mode
        c-eldoc
        coffee-mode
        color-moccur
        company
        cperl-mode
        csv-mode
        deferred
        el-get
        eldoc-extension
        ensime
        etags-table
        expand-region
        fringe-helper
        fuzzy
        git-gutter
        helm
        helm-c-moccur
        helm-perldoc
        highlight-current-line
        inertial-scroll
        init-loader
        jaspace
        js2-highlight-vars
        js2-mode
        js-doc
        judge-indent
        key-chord
        lispxmp
        magit
        markdown-mode
        mode-compile
        moz-repl
        multiple-cursors
        np
        open-junk-file
        package
        paredit
        perl-completion
        php-mode-improved
        pod-mode
        point-undo
        popup
        popwin
        quickrun
        rsense
        rst-mode
        ruby-electric-mode
        scala-mode
        sequential-command
        set-perl5lib
        shadow
        smartchr
        srep
        sudo-ext
        textile-mode
        undo-tree
        uniq
        web-mode
        wrap-region
        yaml-mode
        yasnippet
        zencoding-mode))

(dolist (package bootstrap:packages)
  (el-get-install package))
